import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastProvider } from '@/providers/toast-provider';
import { AuthProvider } from '@/providers/auth-provider';
import { cn } from '@/lib/utils';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body
        className={cn('min-h-full flex flex-col', inter.className)}
        style={{ fontFamily: inter.style.fontFamily }}
      >
        <ToastProvider>
          <AuthProvider>{children}</AuthProvider>
        </ToastProvider>

        {/* <div className="relative w-full min-h-dvh">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="1400"
            height="919"
            viewBox="0 0 2446 919"
            fill="none"
            className="absolute bottom-0 w-full h-dvh"
          >
            <g filter="url(#filter0_f_122_83)">
              <ellipse
                cx="1223"
                cy="999"
                rx="1380"
                ry="499"
                fill="url(#paint0_linear_122_83)"
              />
            </g>
            <defs>
              <filter
                id="filter0_f_122_83"
                x="-657"
                y="0"
                width="3760"
                height="1998"
                filterUnits="userSpaceOnUse"
                colorInterpolationFilters="sRGB"
              >
                <feFlood floodOpacity="0" result="BackgroundImageFix" />
                <feBlend
                  mode="normal"
                  in="SourceGraphic"
                  in2="BackgroundImageFix"
                  result="shape"
                />
                <feGaussianBlur
                  stdDeviation="250"
                  result="effect1_foregroundBlur_122_83"
                />
              </filter>
              <linearGradient
                id="paint0_linear_122_83"
                x1="1223"
                y1="500"
                x2="1223"
                y2="1498"
                gradientUnits="userSpaceOnUse"
              >
                <stop stopColor="oklch(0.5676 0.2021 283.0838)" />
                <stop offset="1" stopColor="oklch(0.6746 0.1414 261.3380)" />
              </linearGradient>
            </defs>
          </svg>
        </div> */}
      </body>
    </html>
  );
}
